CMS-war/src/controllers/CustomerController.java
package controllers;

import java.util.ArrayList;

import javax.el.ELContext;
import javax.enterprise.context.RequestScoped;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedProperty;
import javax.faces.context.FacesContext;
import javax.inject.Named;
import controllers.CustomerApplication;
import mbeans.CustomerManagedBean;

@Named(value = "customerController")
@RequestScoped
public class CustomerController {
	/**
	 * @return the showForm
	 */
	public boolean isShowForm() {
		return showForm;
	}

	/**
	 * @param showForm the showForm to set
	 */
	public void setShowForm(boolean showForm) {
		this.showForm = showForm;
	}

	@ManagedProperty(value = "#{propertyManagedBean}")
	CustomerManagedBean customerManagedBean;

	/**
	 * @return the contactinfor
	 */
	public cms.entities.CustomerContact getContactinfor() {
		return contactinfor;
	}

	/**
	 * @param contactinfor the contactinfor to set
	 */
	public void setContactinfor(cms.entities.CustomerContact contactinfor) {
		this.contactinfor = contactinfor;
	}

	private int customerId; // this customerId is the index, don't confuse with the Property Id
	private int contactId;

	/**
	 * @return the contactId
	 */
	public int getContactId() {
		return contactId;
	}

	/**
	 * @param contactId the contactId to set
	 */
	public void setContactId(int contactId) {
		this.contactId = contactId;
	}

	public int getCustomerId() {
		return customerId;
	}

	public void setCustomerId(int customerId) {
		this.customerId = customerId;
	}

	private cms.entities.Customer customer;
	private ArrayList<cms.entities.CustomerContact> contactPerson;
	private cms.entities.CustomerContact contactinfor;
	private int index = 0;
	private int getId = 0;
	/**
	 * @return the getId
	 */
	public int getGetId() {
		return getId;
	}

	/**
	 * @param getId the getId to set
	 */
	public void setGetId(int getId) {
		this.getId = getId;
	}

	private boolean showForm = true;

	public CustomerController() {
		// Assign customer identifier via GET param
		// this customerId is the index, don't confuse with the Customer Id
		customerId = Integer.valueOf(
				FacesContext.getCurrentInstance().getExternalContext().getRequestParameterMap().get("paramIndex"));
		// Assign customer based on the id provided
		customer = getCustomer();
		contactPerson = getContactPerson();
		contactinfor = getContactPersonInfor();
		// index = getCustomerIndex();
		getId = customerId;
	}

	public cms.entities.Customer getCustomer() {
		if (customer == null) {
			// Get application context bean CustomerApplication
			ELContext context = FacesContext.getCurrentInstance().getELContext();
			CustomerApplication app = (CustomerApplication) FacesContext.getCurrentInstance().getApplication()
					.getELResolver().getValue(context, null, "customerApplication");
			// -1 to propertyId since we +1 in JSF (to always have positive property id!)
			if (app.getCustomers().size() >= --customerId) {
				return app.getCustomers().get(customerId); // this customerId is the index, don't confuse with the
															// Property Id
			}
		}
		return customer;
	}

	public cms.entities.CustomerContact getContactPersonInfor() {
		if (contactinfor == null) {
			// Get application context bean CustomerApplication
			ELContext context = FacesContext.getCurrentInstance().getELContext();
			CustomerApplication app = (CustomerApplication) FacesContext.getCurrentInstance().getApplication()
					.getELResolver().getValue(context, null, "customerApplication");
			int index = 0;
			for (int i = 0; i < app.getContactPerson().size(); i++) {
				if (app.getContactPerson().get(i).getContactId() == customerId) {
					index = i;
					break;
				}
			}
			if(app.getContactPerson().size()==0)//make sure if no contact person infor for certain customer
				return contactinfor;
			else
				return app.getContactPerson().get(index);
		}
		return contactinfor;
	}

	public ArrayList<cms.entities.CustomerContact> getContactPerson() {
		if (contactPerson == null) {
			// Get application context bean CustomerApplication
			ELContext context = FacesContext.getCurrentInstance().getELContext();
			CustomerApplication app = (CustomerApplication) FacesContext.getCurrentInstance().getApplication()
					.getELResolver().getValue(context, null, "customerApplication");
			int id = ++customerId;
			contactPerson = new ArrayList<cms.entities.CustomerContact>();
			for (int i = 0; i < app.getContactPerson().size(); i++) {
				if (app.getContactPerson().get(i).getCustomer().getCusId() == id) {
					contactPerson.add(app.getContactPerson().get(i));
				}
			}
			return contactPerson;
		}
		return contactPerson;
	}

	public int getCustomerIndex(int cus_id) {
		if (index == 0) {
			// Get application context bean CustomerApplication
			ELContext context = FacesContext.getCurrentInstance().getELContext();
			CustomerApplication app = (CustomerApplication) FacesContext.getCurrentInstance().getApplication()
					.getELResolver().getValue(context, null, "customerApplication");
			for (int i = 0; i < app.getCustomers().size(); i++) {
				if (app.getCustomers().get(i).getCusId() == cus_id) {
					index = i;
					break;
				}
			}
			return index;
		}
		return index;
	}

	/**
	 * @param contact Id
	 */
	public void removeContactPerson(cms.entities.CustomerContact contact) {
		try {
			// remove this customer from db via EJB
			int contactId = contact.getContactId();
			int customerId = contact.getCustomer().getCusId();
	        //instantiate customerManagedBean
	        ELContext elContext = FacesContext.getCurrentInstance().getELContext();
	        customerManagedBean = (CustomerManagedBean) FacesContext.getCurrentInstance().getApplication()
	                .getELResolver().getValue(elContext, null, "customerManagedBean");
			customerManagedBean.removeContactPerson(contactId);
			CustomerApplication app = (CustomerApplication) FacesContext.getCurrentInstance().getApplication()
					.getELResolver().getValue(elContext, null, "customerApplication");
			app.searchAll1();
			contactPerson = new ArrayList<cms.entities.CustomerContact>();
			for (int i = 0; i < app.getContactPerson().size(); i++) {
				if (app.getContactPerson().get(i).getCustomer().getCusId() == customerId) {
					contactPerson.add(app.getContactPerson().get(i));
				}
			}
			//index1 = customerId;
			FacesContext.getCurrentInstance().addMessage(null, new FacesMessage("Customer has been deleted succesfully"));
			}
			catch (Exception ex) {
	
	        }
		showForm = true;
	}

}

CMS-war/src/mbeans/CustomerManagedBean.java
package mbeans;

import java.io.Serializable;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.ejb.EJB;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;

import mbeans.CustomerManagedBean;
import repository.interfaces.CustomerRepository;
import cms.entities.Customer;
import cms.entities.CustomerContact;
import cms.entities.NormalUser;
import cms.entities.Address;
import cms.entities.Admin;
import cms.entities.IndustryType;

@ManagedBean(name = "customerManagedBean")
@SessionScoped
public class CustomerManagedBean implements Serializable{
	@EJB
    CustomerRepository customerRepository;
	
	private UIComponent save;
	private UIComponent save1;
	private UIComponent save2;
    /**
     * Creates a new instance of CustomerManagedBean
     */
    public CustomerManagedBean() {
    }

    public List<Customer> getAllCustomers() {
        try {
            List<Customer> customers = customerRepository.getAllCustomers();
            return customers;
        } catch (Exception ex) {
            Logger.getLogger(CustomerManagedBean.class.getName()).log(Level.SEVERE, null, ex);
        }
        return null;
    }
    
    public List<CustomerContact> getAllContactPerson() {
        try {
            List<CustomerContact> contactPerson = customerRepository.getAllContactPerson();
            return contactPerson;
        } catch (Exception ex) {
            Logger.getLogger(CustomerManagedBean.class.getName()).log(Level.SEVERE, null, ex);
        }
        return null;
    }
    
    public void removeCustomer(int cusId) {
        try {
            customerRepository.removeCustomer(cusId);
        } catch (Exception ex) {
            Logger.getLogger(CustomerManagedBean.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void removeContactPerson(int contactId) {
        try {
            customerRepository.removeContactPerson(contactId);
        } catch (Exception ex) {
            Logger.getLogger(CustomerManagedBean.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void editCustomer(Customer customer) {
        try {
            String s = customer.getAddress().getStreetNumber();
            String s1 = customer.getAddress().getStreetAddress();
            String s2 = customer.getAddress().getSuburb();
            String s3 = customer.getAddress().getState();
            String s4 = customer.getAddress().getPostcode();
            Address address = customer.getAddress();
            address.setStreetNumber(s);
            address.setStreetAddress(s1);
            address.setSuburb(s2);
            address.setState(s3);
            address.setPostcode(s4);
            customer.setAddress(address);
            customerRepository.editCustomer(customer);

            FacesMessage message = new FacesMessage("Customer has been updated succesfully");
            FacesContext context = FacesContext.getCurrentInstance();
            context.addMessage(save.getClientId(context), message);
            //FacesContext.getCurrentInstance().addMessage("MyForm:message", new FacesMessage("Customer has been updated succesfully"));
        } catch (Exception ex) {
            Logger.getLogger(CustomerManagedBean.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public void editContactPerson(CustomerContact contactPerson) {
        try {
            customerRepository.editContactPerson(contactPerson);

            FacesMessage message = new FacesMessage("Contact person has been updated succesfully");
            FacesContext context = FacesContext.getCurrentInstance();
            context.addMessage(save1.getClientId(context), message);
            //FacesContext.getCurrentInstance().addMessage("MyForm:message", new FacesMessage("Customer has been updated succesfully"));
        } catch (Exception ex) {
            Logger.getLogger(CustomerManagedBean.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void editIndustryType(IndustryType industryType) {
        try {
            customerRepository.editType(industryType);

            FacesMessage message = new FacesMessage("industry Type has been updated succesfully");
            FacesContext context = FacesContext.getCurrentInstance();
            context.addMessage(save2.getClientId(context), message);
            //FacesContext.getCurrentInstance().addMessage("MyForm:message", new FacesMessage("Customer has been updated succesfully"));
        } catch (Exception ex) {
            Logger.getLogger(CustomerManagedBean.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void removeIndustryType(int inId) {
        try {
            customerRepository.deleteType(inId);
        } catch (Exception ex) {
            Logger.getLogger(CustomerManagedBean.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void addIndustryType(controllers.IndustryType localType) {
        //convert this newCustomer which is the local customer to entity customer
    	IndustryType industryType = convertToEntity2(localType);

        try {
            customerRepository.addType(industryType);
        } catch (Exception ex) {
            Logger.getLogger(CustomerManagedBean.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public void addCustomer(controllers.Customer localCustomer) {
        //convert this newCustomer which is the local customer to entity customer
        Customer customer = convertToEntity(localCustomer);

        try {
            customerRepository.addCustomer(customer);
        } catch (Exception ex) {
            Logger.getLogger(CustomerManagedBean.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void addContactPerson(controllers.ContactPerson localContactPerson) {
        //convert this newContactPerson which is the local contact person to entity customerContact
    	CustomerContact customerContact = convertToEntity1(localContactPerson);

        try {
            customerRepository.addContactPerson(customerContact);
        } catch (Exception ex) {
            Logger.getLogger(CustomerManagedBean.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private IndustryType convertToEntity2(controllers.IndustryType localType) {
    	IndustryType industryType = new IndustryType(); //entity
    	industryType.setIndustryType(localType.getIndustyTypeName());
        return industryType;
    }
    
    private CustomerContact convertToEntity1(controllers.ContactPerson localContactPerson) {
    	CustomerContact customerContact = new CustomerContact(); //entity
    	customerContact.setContactId(localContactPerson.getContactId());
    	customerContact.setAge(localContactPerson.getAge());
    	customerContact.setAvailableTime(localContactPerson.getAvailableTime());
    	customerContact.setGender(localContactPerson.getGender());
    	customerContact.setMobilePhone(localContactPerson.getMobilePhone());
    	customerContact.setName(localContactPerson.getName());
    	customerContact.setCustomer(localContactPerson.getCustomer());
        return customerContact;
    }
    
    private Customer convertToEntity(controllers.Customer localCustomer) {
        Customer customer = new Customer(); //entity
        String streetNumber = localCustomer.getStreetNumber();
        String streetAddress = localCustomer.getStreetAddress();
        String suburb = localCustomer.getSuburb();
        String postcode = localCustomer.getPostcode();
        String state = localCustomer.getState();
        Address address = new Address(streetNumber, streetAddress, suburb, postcode, state);
        customer.setAddress(address);
        customer.setCeo(localCustomer.getCeo());
        customer.setIndustryType(localCustomer.getIndustryType());
        customer.setNoOfPeople(localCustomer.getNoOfPeople());
        customer.setPurchasedProduct(localCustomer.getPurchasedProduct());
        customer.setRegisterDate(localCustomer.getRegisterDate());
        customer.setWebsite(localCustomer.getWebsite());
        customer.setNormalUser(localCustomer.getNormalUser());
        //Date dob = localCustomer.getNormalUser().getDob();
        //BigDecimal salary = localCustomer.getNormalUser().getSalary();
        //Admin admin = localCustomer.getNormalUser().getAdmin();
        //NormalUser normalUser = new cms.entities.NormalUser(dob, salary, admin);
//        int conactPersonId = localProperty.getConactPersonId();
//        String name = localProperty.getName();
//        String phoneNumber = localProperty.getPhoneNumber();
//        ContactPerson contactPerson = new fit5042.tutex.repository.entities.ContactPerson(conactPersonId, name, phoneNumber);
//        if (contactPerson.getConactPersonId() == 0) {
//            contactPerson = null;
//        }
//        property.setContactPerson(contactPerson);
        //customer.setNormalUser(normalUser);
        return customer;
    }

	/**
	 * @return the save
	 */
	public UIComponent getSave() {
		return save;
	}

	/**
	 * @param save the save to set
	 */
	public void setSave(UIComponent save) {
		this.save = save;
	}
	
	
    public List<NormalUser> getAllStaff() throws Exception {
        try {
            return customerRepository.getAllStaff();
        } catch (Exception ex) {
            Logger.getLogger(CustomerManagedBean.class.getName()).log(Level.SEVERE, null, ex);
        }

        return null;
    }

    public List<Admin> getAllAdmin() throws Exception {
        try {
            return customerRepository.getAllAdmin();
        } catch (Exception ex) {
            Logger.getLogger(CustomerManagedBean.class.getName()).log(Level.SEVERE, null, ex);
        }

        return null;
    }
   
    public List<IndustryType> getAllIndustryType() {
        try {

CMS-war/WebContent/admin/contactPersonAdd.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:o="http://omnifaces.org/ui"
	xmlns:of="http://omnifaces.org/functions"
	xmlns:pt="http://xmlns.jcp.org/jsf/passthrough">

<h:head>
	<!-- Required meta tags -->
	<meta charset="utf-8" />
	<meta name="viewport"
		content="width=device-width, initial-scale=1, shrink-to-fit=no" />

	<!-- Bootstrap CSS -->
	<link rel="stylesheet" type="text/css"
		href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" />
	<link
		href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css"
		rel="stylesheet" type="text/css" />
	<link
		href="https://fonts.googleapis.com/css?family=Montserrat:100,200,300,400,500,600,700,800"
		rel="stylesheet" type="text/css" />
	<h:outputStylesheet library="css" name="animate.css"></h:outputStylesheet>
	<h:outputStylesheet library="css" name="main.css"></h:outputStylesheet>
	<link rel="stylesheet"
		href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css" />
	<title>Management System</title>
</h:head>
<h:body>
	<header class="header bg">
		<div class="container text-white">
			<div class="row">
				<div class="col-sm-2 align-self-center text-left">
					<h6>AUSPrintings Pty Ltd</h6>
				</div>
				<div class="col-sm-7 col-12 align-self-center box-1 text-center">
					<h:link class="navbar-brand" outcome="faces/index.xhtml">
						<h:graphicImage value="/resources/images/header-logo.png"
							alt="logo" style="height: 75px;" />
					</h:link>
				</div>
				<div class="col-sm-3 align-self-center text-center">
					<div class="row">
						  <h6>Hello, Admin&#160;&#160;&#160;&#160;<h:outputLink value="${request.contextPath}/logout">Logout</h:outputLink></h6>
					</div>
				</div>
			</div>
			<!--/row-->
		</div>
		<!--container-->
	</header>
	<span class="position-absolute trigger"> <!-- hidden trigger to apply 'stuck' styles -->
	</span>
	<nav class="navbar navbar-expand-sm sticky-top navbar-dark">
		<div class="container">
			<button class="navbar-toggler navbar-toggler-right" type="button"
				data-toggle="collapse" data-target="#navbar1">
				<span class="navbar-toggler-icon"></span>
			</button>
			<div class="collapse navbar-collapse" id="navbar1">
				<ul class="navbar-nav">
					<li class="nav-item"><h:link class="nav-link" outcome="/admin/index.xhtml" value="Home"/></li>
					<li class="nav-item"><h:link class="nav-link" outcome="/admin/customer.xhtml" value="Manage Customer"/></li>
 					<li class="nav-item"><h:link class="nav-link" outcome="/admin/industry.xhtml" value="Manage Industry Type"/></li>
 					<li class="nav-item"><h:link class="nav-link" outcome="/admin/normalUser.xhtml" value="Manage Normal User" /></li>
				</ul>
			</div>
		</div>
		<!--container end-->
	</nav>
	<div id="about-us" style="padding-top: 100px; padding-bottom: 400px;">
		<div class="container">
			<div class="navbar navbar-inverse">
				<h3>Add a new Contact Person</h3>
			</div>
			<div>
				<f:view>
					<h:form>
						<h:message for="submit" globalOnly="true"
							style="color:blue;font-weight: bold;" />
						<table class="table table-bordered ">
							<tr>
								<td width="200"><h:outputLabel value="Contact Name:"
										for="name" /></td>
								<td><h:inputText id="name" value="#{contactPerson.name}"
										title="name" required="true"
										requiredMessage="Please enter a Contact Name"
										validatorMessage="Only numbers, letters and whitespaces are accepted for Contact Name"
										pt:placeholder="Jack MA">
										<f:validateRegex pattern="^([a-zA-Z0-9]+(.)?)+$" />
										<!-- dot:Matches any character except linebreaks. ? Matches 0 or 1 of the preceding token, effectively making it optional.-->
									</h:inputText> <h:outputText value="&#160;&#160;&#160;&#160;&#160;&#160;" />
									<h:message for="name" style="color:red;font-weight: bold;" /></td>
							</tr>
							<tr>
								<td width="200"><h:outputLabel value="Age:" for="age" /></td>
								<td valign="bottom"><h:inputText id="age"
										value="#{contactPerson.age}"
										converterMessage="Please enter a valid age"
										pt:placeholder="30">
										<o:validator validatorId="javax.faces.Required"
											message="Please enter a age" />
										<o:validator validatorId="javax.faces.LongRange" minimum="1"
											message="Age must be greater than 0" />
										<!-- <f:validateLongRange minimum="1" /> -->
									</h:inputText> <h:outputText value="&#160;&#160;&#160;&#160;&#160;&#160;" />
									<!-- &#160; is the numeric entity reference (meant to be easily parseable by machines). -->
									<h:message for="age" style="color:red;font-weight: bold;" /></td>
							</tr>
							<tr>
								<td width="100"><h:outputLabel
										value="Contact Available Time:" for="availableTime" /></td>
								<td valign="bottom"><h:inputText id="availableTime"
										value="#{contactPerson.availableTime}" required="true"
										requiredMessage="Please enter a contact available time!"
										pt:placeholder="Monday-Friday 14:00-16:00"></h:inputText> <h:outputText
										value="&#160;&#160;&#160;&#160;&#160;&#160;" /> <!-- &#160; is the numeric entity reference (meant to be easily parseable by machines). -->
									<h:message for="availableTime"
										style="color:red;font-weight: bold;" /></td>
							</tr>
							<tr>
								<td width="100"><h:outputLabel value="Gender:" for="gender" /></td>
								<td valign="bottom"><h:inputText id="gender"
										value="#{contactPerson.gender}" required="true"
										validatorMessage="Please enter a valid gender(Only accept alphabet, no case sensitive)"
										requiredMessage="Please enter a gender" pt:placeholder="VIC">
										<f:validateRegex pattern="^([a-zA-Z]+)$" />
									</h:inputText> <h:outputText value="&#160;&#160;&#160;&#160;&#160;&#160;" />
									<!-- &#160; is the numeric entity reference (meant to be easily parseable by machines). -->
									<h:message for="gender" style="color:red;font-weight: bold;" />
								</td>
							</tr>
							<tr>
								<td width="100"><h:outputLabel value="Phone Number:"
										for="mobilePhone" /></td>
								<td valign="bottom"><h:inputText id="mobilePhone"
										value="#{contactPerson.mobilePhone}" required="true"
										converterMessage="Please enter a valid phone number"
										validatorMessage="Please enter a valid phone number(Only accept numbers)"
										requiredMessage="Please enter a phone number"
										pt:placeholder="0420507833">
										<f:validateLongRange minimum="1" />
									</h:inputText> <h:outputText value="&#160;&#160;&#160;&#160;&#160;&#160;" />
									<!-- &#160; is the numeric entity reference (meant to be easily parseable by machines). -->
									<h:message for="mobilePhone"
										style="color:red;font-weight: bold;" /></td>
							</tr>
							<tr>
								<td><h:outputLabel
										value="You are adding a new contact person for the user with id &#160;#{customerController.getId} Please select #{customerController.getId} to confirm!"
										for="contact" /></td>
								<td><h:selectOneMenu id="contact"
										value="#{contactPerson.customer}"
										converter="contactPersonConverter">
										<f:selectItem itemValue="#{null}" itemLabel="--select--" />
										<f:selectItems value="#{customerManagedBean.allCustomers}"
											var="c" itemLabel="#{c.cusId}" itemValue="#{c}" />
									</h:selectOneMenu></td>
							</tr>
						</table>
						<h:commandButton id="submit" value="Submit"
							action="#{addContactPerson.addNewContactPerson(contactPerson)}"
							binding="#{addContactPerson.submit}" class="btn btn-primary"
							style="margin-right:20px">
							<f:param name="paramIndex"
								value="#{customerController.getId}" />
						</h:commandButton>
						<h:link id="close" value="Close"
							outcome="/admin/contactPerson.xhtml" class="btn btn-primary">
							<f:param name="paramIndex"
								value="#{customerController.getId}" />
						</h:link>

					</h:form>

				</f:view>
			</div>
		</div>
	</div>
	<section class="section-7">
		<!-- Footer -->
		<footer class="page-footer font-small stylish-color-dark">
			<!-- Copyright -->
			<div class="footer-copyright text-center">
				<div class="gradient"></div>
				<p>
					© 2020,&#160;&#160;FIT5042-Assignment,&#160;&#160;designed by Rock Liu
				</p>
			</div>
			<!-- Copyright -->

		</footer>
		<!-- Footer -->
	</section>
	<!-- Optional JavaScript -->
	<!-- jQuery first, then Popper.js, then Bootstrap JS -->

	<script type="text/javascript"
		src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
	<script type="text/javascript"
		src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
	<script type="text/javascript"
		src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
	<h:outputScript library="js" name="animate.js" />
	<h:outputScript library="js" name="custom.js" />
	<script type="text/javascript"
		src="https://code.jquery.com/jquery-1.12.4.js" />
	<script type="text/javascript"
		src="https://code.jquery.com/ui/1.12.1/jquery-ui.js" />
	<h:outputScript library="js" name="formatDatePicker.js" />
</h:body>
</html>